[global]
# Configurações globais do Streamlit
developmentMode = false
logLevel = "info"

[server]
# Configurações do servidor
port = 8501
address = "0.0.0.0"
maxUploadSize = 200
maxMessageSize = 200
enableCORS = false
enableXsrfProtection = true
enableWebsocketCompression = true

[browser]
# Configurações do navegador
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
# Configurações do tema
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[runner]
# Configurações do runner
magicEnabled = true
installTracer = false
fixMatplotlib = true
postScriptGC = true
fastReruns = true
enforceSerializableSessionState = true

[client]
# Configurações do cliente
caching = true
displayEnabled = true
showErrorDetails = true
toolbarMode = "viewer"
