[server]
maxUploadSize = 400
enableCORS = false
enableXsrfProtection = true

[client]
caching = true
showErrorDetails = false
toolbarMode = "auto"

[runner]
fastReruns = true
enforceSerializableSessionState = false

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[browser]
gatherUsageStats = false
